MeetingManager/Presentation/MeetingManager.Presentation/Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MeetingManager.Common.EntityModel;
using MeetingManager.Domain.Services;
using MeetingManager.Presentation.Models;
using MeetingManager.Presentation.Models.Mappings;

namespace MeetingManager.Presentation.Controllers
{
    public class MeetingController : BaseController
    {
        private readonly IMeetingService _meetingService;

        public MeetingController(IMeetingService meetingService)
        {
            _meetingService = meetingService;
        }

        /// <summary>
        /// Renders view with all meetings.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var meetings = _meetingService.GetAllMeetings()
                .Select(meeting => new MeetingListModel()
                                   {
                                       Creator = meeting.Creator.Name,
                                       MeetingTime = meeting.MeetingTime.ToString("g"),
                                       ParticipantsCount = meeting.Participants == null ? 0 : meeting.Participants.Count,
                                       Subject = meeting.Subject,
                                       Id = meeting.Id
                                   });



            return View(meetings);
        }

        /// <summary>
        /// Renders empty view for creating new meeting
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            var currentUser = GetCurrentUser();

            if (currentUser == null) return RedirectToAction("Index", "Home");
            
            ViewBag.IsCreate = true;
            var availableUsers =
                _meetingService.GetAllUsers()
                    .Where(user => user.Name != currentUser.Name)
                    .Select(user => new ParticipantModel() {Id = user.Id, Name = user.Name})
                    .ToList();

            currentUser.IsCreator = true;
            
            var model = new MeetingModel
                        {
                            AvailableUsers = availableUsers,
                            Participants = new List<ParticipantModel> {currentUser}
                        };

            return View("EditMeeting", model);
        }

        /// <summary>
        /// Retrieves the meeting by it's id and renders the view for editing that meeting
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var currentUser = GetCurrentUser();
            if (currentUser == null) return RedirectToAction("Index", "Home");

            var meeting = _meetingService.GetMeetingById(id);

            if (meeting == null) return RedirectToAction("Index");

            var model = meeting.ToModel();
            var participantIds = model.Participants.Select(participantModel => participantModel.Id).ToList();
            model.AvailableUsers =
                _meetingService.GetAllUsers()
                    .Where(user => !participantIds.Contains(user.Id))
                    .Select(Mapper.Map<ParticipantModel>)
                    .ToList();

            return View("EditMeeting", model);
        }

        /// <summary>
        /// Saves the meeting which was edited in the view
        /// If there are errors renders same view with the errors
        /// </summary>
        /// <param name="meeting"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(MeetingModel meeting)
        {
            ViewBag.IsCreate = ViewBag.IsCreate;
            if (!ModelState.IsValid)
            {
                ViewBag.IsCreate = true;
                return View("EditMeeting", meeting);
            }

            if (meeting.Participants == null || meeting.Participants.Count < 2)
            {
                ModelState.AddModelError("Participants", "Meeting must have at least two participants");
                return View("EditMeeting", meeting);
            }

            var currentUser = GetCurrentUser();

            var entity = meeting.ToEntity();

            entity.Creator = _meetingService.GetUserById(currentUser.Id);
            entity.Participants = new List<User>();
            foreach (var participantModel in meeting.Participants)
            {
                entity.Participants.Add(_meetingService.GetUserById(participantModel.Id));
            }

            var saved = _meetingService.SaveMeeting(entity);

            return View("SuccessCreateMeeting", saved.Id);
        }

        /// <summary>
        /// Delete single meeting from database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            _meetingService.RemoveMeeting(id);

            return RedirectToAction("Index");
        }

	}
}

MeetingManager/Presentation/MeetingManager.Presentation/Views/Meeting/EditMeeting.cshtml
@using MeetingManager.Presentation.Models
@model MeetingManager.Presentation.Models.MeetingModel

<div class="row" id="meeting-wrapper">
    <div class="col-md-12">
        <h3>Save your meeting</h3>
        <hr />
    </div>

    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("Save", "Meeting", FormMethod.Post, new { @class = "form-horizontal", id = "meetingForm", @data_bind = "submit: saveMeeting" }))
            {
                <div class="form-group">
                    <label for="Subject" class="control-label col-md-3">Subject</label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="MeetingTime" class="control-label col-md-3">Meeting time</label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.MeetingTime, new { @class = "form-control", @type = "datetime" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="description" class="control-label col-md-3">Description</label>
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Description, new { @rows = "3", @class = "form-control" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Id)
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-default">Save</button>
                        @Html.ActionLink("Cancel", "Index", "Meeting", new { }, new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
            @Html.ValidationSummary(false)

        </div>
        <div class="col-md-6">
            <div class="row">
                <div id="participants" class="col-md-6">
                    <h4><span>Meeting participants</span></h4>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>User name</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody data-bind="foreach: participants">
                            <tr>
                                <td><span data-bind="text: $index"></span></td>
                                <td><span data-bind="text: Name"></span></td>
                                <td>
                                    <button class="btn btn-xs btn-danger" data-bind="click: $parent.removeUserEventHandler, disable: IsCreator">
                                        <span class="glyphicon glyphicon-minus"></span> Remove
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div id="availableUsers" class="col-md-6">
                    <h4><span>Available users</span></h4>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>User name</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody data-bind="foreach: availableUsers">
                            <tr>
                                <td><span data-bind="text: $index"></span></td>
                                <td><span data-bind="text: Name"></span></td>
                                <td>
                                    <button class="btn btn-xs btn-danger" data-bind="click: $parent.addUserEventHandler">
                                        <span class="glyphicon glyphicon-plus"></span> Add
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @if ((Session["user"] as ParticipantModel).Id == Model.CreatorId)
    {
        <hr />
        <div class="row">
            <p>Want to notify them about the meeting? Just type the message here:</p>
            <div class="col-md-12">
                <form class="form-inline">
                    <div class="form-group">
                        <label class="sr-only" for="message">Message</label>
                        <input type="text" id="message" name="message" class="form-control" />
                    </div>
                    <button class="btn btn-default" type="button" data-bind="click: notifyParticipants">Notify</button>
                </form>
            </div>
        </div>
    }


</div>

@section scripts
{
    <script type="text/javascript">
        (function (app) {
            app.MeetingViewModel.initAvailableUsers(@Html.Raw(Json.Encode(Model.AvailableUsers)));
            app.MeetingViewModel.initParticipants(@Html.Raw(Json.Encode(Model.Participants)));

            ko.applyBindings(app.MeetingViewModel);

            $(function () {
                $('#MeetingTime').datetimepicker();
            });
        })(window.app = window.app || {});
    </script>
}

MeetingManager/Presentation/MeetingManager.Presentation/Views/Meeting/Index.cshtml
@model IEnumerable<MeetingManager.Presentation.Models.MeetingListModel>

<div class="row">
    <div class="col-md-12">
        <h3>All meetings</h3>
        <hr />  
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Time</th>
                    <th>Creator</th>
                    <th>#Participants</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var meeting in Model)
                {
                    <tr>
                        <td>
                            @meeting.Subject
                        </td>
                        <td>
                            @meeting.MeetingTime
                        </td>
                        <td>
                            @meeting.Creator
                        </td>
                        <td>
                            @meeting.ParticipantsCount
                        </td>
                        <td>
                            @Html.ActionLink("Remove", "Delete", "Meeting", new { @id = meeting.Id }, new { @class = "btn btn-danger" })
                            @Html.ActionLink("Edit", "Edit", "Meeting", new { @id = meeting.Id }, new { @class = "btn btn-default" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("Create new", "Create", "Meeting", new { }, new { @class = "btn btn-default" })
    </div>
</div>

MeetingManager/Presentation/MeetingManager.Presentation/Views/Meeting/SuccessCreateMeeting.cshtml
@model int

<section>
    <p> Successfully created meeting </p>
    @Html.ActionLink("Back", "Index", "Meeting",new{}, new { @class = "btn btn-default" })

    
</section>

@section scripts
{
    <script type="text/javascript">
        window.app.NotificationViewModel.notifyCreateMeeting(@Model);
    </script>
}